// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow() {
  return window['go']['window']['Window']['HideWindow']();
}

export function SetContext(arg1) {
  return window['go']['window']['Window']['SetContext'](arg1);
}

export function SetWindowAlwaysOnTop(arg1) {
  return window['go']['window']['Window']['SetWindowAlwaysOnTop'](arg1);
}

export function ShowWindow() {
  return window['go']['window']['Window']['ShowWindow']();
}
