// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindow() {
  return window['go']['window']['Window']['GetWindow']();
}

export function HideWindow() {
  return window['go']['window']['Window']['HideWindow']();
}

export function SetContext(arg1, arg2) {
  return window['go']['window']['Window']['SetContext'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['window']['Window']['ShowWindow']();
}
