// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function HideWindow():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetWindowAlwaysOnTop(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;
