// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {window} from '../models';
import {context} from '../models';

export function GetWindow():Promise<window.Window>;

export function HideWindow():Promise<void>;

export function SetContext(arg1:context.Context,arg2:window.Data):Promise<void>;

export function ShowWindow():Promise<void>;
