// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';

export function GetNewApp():Promise<menu.Menu>;

export function Greet(arg1:string):Promise<string>;

export function RandomGrandLotto(arg1:number):Promise<Array<any>>;

export function Test(arg1:string):Promise<string>;
