// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['OtherApp']['Greet'](arg1);
}

export function RandomGrandLotto(arg1) {
  return window['go']['main']['OtherApp']['RandomGrandLotto'](arg1);
}

export function Test(arg1) {
  return window['go']['main']['OtherApp']['Test'](arg1);
}
